"""Turn the tables of results/REPORT.md into LaTeX (paper/tables/appendix_tables.tex), so that no number in the
appendix of the paper is typed by hand.

    uv run python -m npf.report > results/REPORT.md && uv run python -m npf.paper_tables
"""
import re
from pathlib import Path

REPLACE = [("±", r"$\pm$"), ("ᵀ", r"$^\top$"), ("→", r"$\to$"), ("·", r"$\cdot$"), ("%", r"\%"), ("_", r"\_"), ("&", r"\&"),
           ("≥", r"$\ge$"), ("≤", r"$\le$"), ("×", r"$\times$"), ("–", "--"), ("#", r"\#"), ("σ", r"$\sigma$"), ("²", r"$^2$")]


def tex(text):
    text = re.sub(r"\*\*(.+?)\*\*", r"\\textbf{\1}", text.strip())
    text = re.sub(r"`(.+?)`", r"\1", text)
    for old, new in REPLACE:
        text = text.replace(old, new)
    return re.sub(r"(\d)e-0?(\d+)", r"\1e-\2", text)


def tables(markdown):
    """Yields (title, header cells, rows, notes) for every '###' section that contains a markdown table."""
    for block in re.split(r"\n(?=#{2,3} )", markdown):
        lines = block.strip().splitlines()
        if not lines or not lines[0].startswith("#"):
            continue
        rows = [[c for c in line.strip().strip("|").split("|")] for line in lines if line.startswith("|")]
        notes = [line for line in lines[1:] if line.strip() and not line.startswith("|")]
        if len(rows) >= 3:
            yield lines[0].lstrip("# ").strip(), rows[0], rows[2:], notes


def main(report="results/REPORT.md", out="paper/tables/appendix_tables.tex"):
    parts = []
    for k, (title, header, rows, notes) in enumerate(tables(Path(report).read_text())):
        spec = "l" + "r" * (len(header) - 1)
        body = " \\\\\n".join(" & ".join(tex(c) for c in row) for row in rows)
        caption = tex(title) + (". " + " ".join(tex(n) for n in notes) if notes else ".")
        parts.append("\n".join([
            r"\begin{table}[h]", r"\caption{" + caption + "}", rf"\label{{tab:app{k}}}", r"\centering\scriptsize\setlength{\tabcolsep}{3pt}",
            r"\resizebox{\ifdim\width>\textwidth\textwidth\else\width\fi}{!}{%", rf"\begin{{tabular}}{{{spec}}}", r"\toprule",
            " & ".join(tex(c) for c in header) + r" \\", r"\midrule", body + r" \\", r"\bottomrule", r"\end{tabular}}", r"\end{table}", ""]))
    Path(out).parent.mkdir(parents=True, exist_ok=True)
    Path(out).write_text("% generated by npf/paper_tables.py from results/REPORT.md - do not edit\n\n" + "\n".join(parts))
    print(f"wrote {len(parts)} tables to {out}")


if __name__ == "__main__":
    main()
